apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc1.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc1.size }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc2.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc2.size }}
  storageClassName: manual

