apiVersion: batch/v1
kind: Job
metadata:
  name: superset-init-job
spec:
  template:
    spec:
      containers:
        - name: superset-init-job
          image: {{ .Values.job.image }}
          command: ["/bin/sh"]                   # {  { .Values.job.command | toYaml | indent 12}  }
          args: ["-c", "ls /;ls /host; sleep 36000; cp -r /host/* /data;"]               # # {  { .Values.job.args | toYaml | indent 12}  }
          volumeMounts:
            - name: host-pvc
              mountPath: {{ .Values.job.srcMountPath }}
            - name: data-pvc
              mountPath: {{ .Values.job.tgtMountPath }}
      restartPolicy: Never
      volumes:
        - name: host-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc1.name }}
        - name: data-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc2.name }}
