apiVersion: batch/v1
kind: Job
metadata:
  name: copy-files-job
spec:
  template:
    spec:
      containers:
        - name: copy-files
          image: {{ .Values.job.image }}
          command: ["/bin/sh"] # {{ .Values.job.command | toYaml | indent 12}}
          args: ["-c", "cp -r /host/* /data"] # {{ .Values.job.args | toYaml | indent 12}}
          volumeMounts:
            - name: host-pv
              mountPath: {{ .Values.job.hostMountPath }}
            - name: data-pvc
              mountPath: {{ .Values.job.volumeMountPath }}
      restartPolicy: Never
      volumes:
        - name: host-pv
          hostPath:
            path: {{ .Values.pv.hostPath }}   # Reference the actual PVC for the host-pv
        - name: data-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}  # Reference the actual PVC for the data-pvc
