# Define the PV name
pv1:
  name: host-pv
  size: 1Gi
  hostPath: /mnt/src

# Define the PVC name
pvc1:
  name: host-pvc
  size: 1Gi

pv2:
  name: data-pv
  size: 1Gi
  hostPath: /mnt/tgt

# Define the PVC name
pvc2:
  name: data-pvc
  size: 1Gi

# Container that performs the copy operation
job:
  image: alpine
  srcMountPath: /host
  tgtMountPath: /data