# Define the PV name
pv:
  name: host-pv
  size: 1Gi
  hostPath: /Users/mustafa/Documents/starrocks-project/superset-initialization/config

# Define the PVC name
pvc:
  name: data-pvc
  size: 1Gi
  storageClass: standard

# Container that performs the copy operation
job:
  image: busybox
  command: ["/bin/sh"]
  args: ["-c", "cp -r /host/* /data"]
  volumeMountPath: /data
  hostMountPath: /host