table_name: Untitled Query 1
main_dttm_col: created_at
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: retail
sql: SELECT * from users ;
params: null
template_params: null
filter_select_enabled: true
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 6953ccc6-7312-47d1-965b-eaeac0965c9b
metrics:
- metric_name: count
  verbose_name: COUNT(*)
  metric_type: count
  expression: COUNT(*)
  description: null
  d3format: null
  currency: null
  extra: null
  warning_text: null
columns:
- column_name: created_at
  verbose_name: null
  is_dttm: true
  is_active: true
  type: DATE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: user_name
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VAR_STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: email
  verbose_name: null
  is_dttm: false
  is_active: true
  type: VAR_STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
- column_name: user_id
  verbose_name: null
  is_dttm: false
  is_active: true
  type: LONG
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra: null
version: 1.0.0
database_uuid: f54e6289-1d9c-4b03-a622-6fdee1413078
